platform :ios, '7.0'
pod 'MagicalRecord', '~> 2.2'
pod 'ProgressHUD', '~> 0.0.1'
pod 'NSDate+TimeAgo', '~> 1.0.2'
pod 'MMPickerView', '~> 0.0.1'
pod 'VPPLocation'
pod 'APParallaxHeader'
pod 'THLabel'
pod 'TBImagePickerController'
pod 'BYLBadgeView'
pod 'CHTTextView'
pod 'HexColors'
pod 'DALinedTextView'
pod 'CKCalendar'
pod 'BKECircularProgressView'
pod "AFNetworking", "~> 2.0"
pod "SKBounceAnimation"
pod 'BBBadgeBarButtonItem'
pod 'TMCache'
pod 'NSData+MD5Digest'
pod 'Reachability'
pod 'OHAttributedLabel'